### ISSUE TITLE
Define some new goals for new features

### ISSUE THREAD

**Issue by pedroalvesbatista** [ArjenSchwarz/aqua#2]
Here we can extend Aqua for some more declarative ways, like manifests in YAML so Aqua can provide more advanced capabilities when integrating with API Gateway and Lambda :

- Divide both API Gateway and Lambda in two manifests (aqua_lamba.yml and aqua_gateway.yml) containing all the details for routing, lambda calls, returning types etc;
- Possible pipeline integration, so Lambda can stream transformations and more complex stuff to another parties of the stack (aqua_stream or aqua_pipeline.yml);
- Some integration with OpenAPI and Swagger, so all the boilerplate details leaved with those and take care of the pushing issues;
- Support for other cloud providers, or at least a CloudFoundry-like o be used in other cloud providers that supports lambdas;
- Integration or interfacing with OpenWhisky, that is a project to support serverless in a self-service manner.

I see these all challenging stuff, so I would like to put my hands dirty on this !

**Comment by ArjenSchwarz** [comment]
Hi @pedroalvesbatista,

Thanks for your interest! I admit your ideas sound interesting. To be honest though, with SAM being introduced, and then having matured into a capable solution, in the two years since I wrote this I have personally stopped using Aqua. 

If you are interested in doing work on this, I certainly won't stop you, but in that case it might be best if you fork the project and run it yourself. That way you won't have to deal with any delays introduced by me. I'd even happily put a note in the README to point at your repo as the preferred one.

**Comment by pedroalvesbatista** [comment]
Hey @ArjenSchwarz !

Thanks for the reply ! I would like to thankyou once more for the excelent idea and usefulness with this project, really pioneer and sharp. I'll fork it and start to work on it right the way. And would be thankful again with the mention in README.

**Comment by ArjenSchwarz** [comment]
Hi @pedroalvesbatista, I have updated the README to refer people to your fork. Thanks for picking this up.
